name: Docker Image CI

on:
  push:
    branches: "**"
  
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Dockerhub login 
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build sampleapp wisecow image 
      run: docker build . -f Dockerfile -t srikanthsathiraju/sampleapp-wisecow:latest 

    - name: Push sampleapp wisecow image to dockerhub 
      run: docker push srikanthsathiraju/sampleapp-wisecow:latest 
